config/routes.rb
AmchartsExample::Application.routes.draw do
  root :to => 'am_charts#welcome'
  match '/hours', to: 'am_charts#hours'

  

end

app/controllers/am_charts_controller.rb
require 'create_json'
require 'calculate_data'

class AmChartsController < ApplicationController
  
  def welcome   
  end
  
  def hours
    # ************************get selector sessions 【選択された項目名】***************************
    if params[:typecolumn1].blank? then

    else
      session[:typecolumn1] = params[:typecolumn1]
    end
    
    @type1_value = if session[:typecolumn1].blank?
      "AIR"
    else
      session[:typecolumn1] 
    end
    
    if params[:typecolumn2].blank? then

    else
      session[:typecolumn2] = params[:typecolumn2]
    end
    
    @type2_value = if session[:typecolumn2].blank?
      "AIR"
    else
      session[:typecolumn2] 
    end
    # **********↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑*********
    
    # ************************get selector sessions 【選択された日付と時間】***************************
    if params[:start_dt].blank? then

    else
      session[:start_dt] = params[:start_dt]
    end
    
    @start_dt = if session[:start_dt].blank?
      @start_dt_html = "2013-06-05"
      "2013/6/5"
    else
      @start_dt_html = session[:start_dt]
      year, month, day = session[:start_dt].split("-")
      year << "/" << sprintf("%d", month) << "/" << sprintf("%d", day) 
    end
    
    #--------------------------------
    if params[:finish_dt].blank? then
    
    else
      session[:finish_dt] = params[:finish_dt]
    end
    
    @finish_dt = if session[:finish_dt].blank?
      @finish_dt_html = "2013-06-05"
      "2013/6/5"
    else
      @finish_dt_html = session[:finish_dt]
      year, month, day = session[:finish_dt].split("-")
      year << "/" << sprintf("%d", month) << "/" << sprintf("%d", day)
    end
    
    #--------------------------------
    if params[:start_hm].blank? then

    else
      session[:start_hm] = params[:start_hm]
    end
    
    @start_hm = if session[:start_hm].blank?
      "0:00"
    else
      session[:start_hm]
    end
    
    #--------------------------------
    if params[:finish_hm].blank? then

    else
      session[:finish_hm] = params[:finish_hm]
    end
    
    @finish_hm = if session[:finish_hm].blank?
      "0:59"
    else
      session[:finish_hm]
    end 
    # **********↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑*********
    
    
    # ************************計算メソッドとcreate_json()を呼び出し***************************
    selHeader_arr = [@type1_value, @type2_value]
    selTime_arr = ["#{@start_dt} #{@start_hm}", "#{@finish_dt} #{@finish_hm}"]
    result_hash = Cal.new.getResult("public/data/CSV_2013060500.csv", selHeader_arr, selTime_arr)
    result = create_json(result_hash)
    @json_val = result[0]
    @json_arr = result[1]
    @max = result[2]
    @headers = result[3]
    @timeshow = result[4]
    @suffix = result[5]
   
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/am_charts_helper.rb
module AmChartsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/am_charts/hours.html.erb
<%= javascript_include_tag 'amcharts' %>
<%= javascript_include_tag 'cust_amcharts'%>
<%= javascript_include_tag 'form'%>
<%= javascript_include_tag 'bootstrap'%>
<script type="text/javascript">
//**************************************************
//計算結果
//**************************************************
var chartData   = <%= @json_val %>;															//if categoryAxis is string format	add .html_safe											
var names       = <%= @json_arr.to_json.html_safe %>;
var max         = <%= @max.to_json.html_safe %>;	
var headers     = <%= @headers.to_json.html_safe%>;
var timeshow    = <%= @timeshow.to_json.html_safe%>;
var suffix      = <%= @suffix %>;

//**************************************************
//画面フォーム初期値
//**************************************************
var type1       = <%= @type1_value.to_json.html_safe%>;
var type2       = <%= @type2_value.to_json.html_safe%>;
var start_dt    = <%= @start_dt_html.to_json.html_safe%>;
var start_hm    = <%= @start_hm.to_json.html_safe%>;
var finish_dt   = <%= @finish_dt_html.to_json.html_safe %>;
var finish_hm   = <%= @finish_hm.to_json.html_safe %>;
var chart;
var graph;
</script>


<!-- フォーム　-->
<div class="row" >
	<form id="form">
		
	
	
	<div class="span4">
		<!-- new -->
		<div class="input-prepend">
			<div class="btn-group">
			  <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#">
			    <i class="icon-list-alt icon-white"></i>  項目名
			    <span class="caret"></span>
			  </a>
			  <ul class="dropdown-menu" id="ul1" style="text-align: center;">
			    <!-- find dropdown menu in form.js -->
			    
			  </ul>
			  <input id="typecolumn1" name="typecolumn1" type="text" placeholder="  項目名を選択してください　" style="width: 150px;">
			</div>
		</div>
		
		<div class="input-prepend">
			<div class="btn-group">
			  <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#">
			    <i class="icon-list-alt icon-white"></i>  項目名
			    <span class="caret"></span>
			  </a>
			  <ul class="dropdown-menu" id="ul2" style="text-align: center;">
			    <!-- find dropdown menu in form.js -->
			  </ul>
			  <input id="typecolumn2" name="typecolumn2" type="text" placeholder="  項目名を選択してください　" style="width: 150px;">
			</div>
		</div>
		<!-- /new -->
		
		<!-- 項目名 <select style="border: 1px solid blue" id="typecolumn1" name="typecolumn1"></select></br> -->
		<!-- 項目名 <select id="typecolumn2" name="typecolumn2"></select> -->
	</div>
	<div class="span4">
   		<div class="input-prepend"><a class="btn btn-info">開始日付</a><input id="start_dt" type="date" name="start_dt" style="width: 150px;" onchange="startTimeChange()"> <input id="start_hm" type="text" name="start_hm" style="width: 50px;"></div>
   	    <div class="input-prepend"><a class="btn btn-info">終了日付 </a><input id="finish_dt" type="date" name="finish_dt" style="width: 150px;"> <input id="finish_hm" type="text" name="finish_hm" style="width: 50px"></div>          
	</div> 		
	<div class="span1">
	  <div class="btn-group" style="width: 100px;">
	  <a class="btn btn-warning dropdown-toggle" data-toggle="dropdown" href="#">
	    <i class="icon-pencil icon-white"></i>  計算
	    <span class="caret"></span>
	  </a>
	  <ul class="dropdown-menu">
	    <li>&nbsp;&nbsp;&nbsp;<i class="icon-list"></i> 計算方法選択</li>
	    <li class="divider"></li>
	    <li><a href="javascript:submit()"><i class="icon-play"></i> 合計</a></li>
	    <li><a href="#"><i class="icon-play"></i> 平均</a></li>
	    <li><a href="#"><i class="icon-play"></i> 最大最小値</a></li>
	  </ul>
	  </div>
	</div>
	</form>
</div>

<div class="row" style="width: 1100px;">
	<!-- amchartsタイプ設定　-->
	<div class="span2" style="padding-top: 50px;">
		<input type="radio" checked="true" name="graph3d" id="graph3d_true" onclick="setGraph3D()">3D
		<input type="radio" name="graph3d" id="graph3d_false" onclick="setGraph3D()">2D　<br/><br/>
		<input type="radio" checked="true" name="graphtype" id="graphtype_column" onclick="setGraphtype()">column
		<input type="radio" name="graphtype" id="graphtype_line" onclick="setGraphtype()">line　<br/><br/>
		<input type="radio" checked="true" name="showLable" id="label_hide" onclick="setLabel()">ラベルを隠し<br/>
		<input style="vertical-align: bottom;" type="radio" name="showLable" id="label_show" onclick="setLabel()">ラベルを表示
	</div>
	<!-- amcharts -->
	<div class="span10" id="chartdiv" class="chartdiv" style=" height:350px; width: 900px;"></div>
</div>

<!-- error div -->
<div id="error_msg" class="alert alert-error" style="position:absolute; top: 0px; left: 720px;  height: 100px; width: 250px;">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4>Warning!</h4>
  　指定された日付にはデータがない
  please choose again
</div>

app/views/am_charts/welcome.html.erb
<%= link_to "計算サンプル", hours_path, class: "btn btn-large btn-primary" %><br/><br/>


app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <h2><%= link_to " AmCharts Sample 07/18", "#" %></h2>
      <nav>
      	<ul class="nav pull-left">
          <li><a href="http://localhost:3000/"><i class="icon-home icon-white"></i> Home</a></li>
          <li><a href="http://localhost:3000/"><i class="icon-signal icon-white"></i> サンプル</a></li>
          <li><%= link_to "Help", 'http://www.amcharts.com/' %></li>
        </ul>  	
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if it IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>AmchartsExample</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  </head>

  <body>
	<%= render 'layouts/header' %>
    <div class="all" >
      <%= yield %>
      <!--<%= render 'layouts/footer' %>-->
	</div>
  </body>
</html>